### ISSUE TITLE
Linux Tests for v3.2

### ISSUE THREAD

**Issue by Iripi97** [mit-ll/CEP#11]
Is running _cep_diag_ still broken for v3.2? I successfully program my VC707 and get all the way through the booting process but fail when trying to run the test suite. Any response would be greatly appreciated.

**Comment by bchetwynd** [comment]
Per the release notes:

v3.2 - (16 April 2021)

LLKI bug fixes
Scratchpad RAM added
Cadenece xcelium simulator and coverage support added
Linux tests updated and expanded
New tests added to cosim focused on LLKI and Scratchpad RAM

There are some lingering segfaults in cep_diag, which we are working to fix in v3.3.  You should be able to run all the tests at least once, but multiple loops have the segfault risk

**Comment by Iripi97** [comment]
I had read that and didn't see any known issues for cep_diag that is why I was asking. I hope I am just an outlier case... here was my output:
![image](https://user-images.githubusercontent.com/26089744/116610050-b52f5300-a8fa-11eb-88e0-f5f825936dfc.png)
That is what I am getting when trying to run the tests. In any case, I am excited for v3.3!

**Comment by Iripi97** [comment]
@bchetwynd Thanks!
I think I just missed this part:
![image](https://user-images.githubusercontent.com/26089744/116611624-34715680-a8fc-11eb-8272-a52538824663.png)
I am rebuilding now and will close the issue if this fixes it!

**Comment by Iripi97** [comment]
Running beautifully, thanks!
![image](https://user-images.githubusercontent.com/26089744/116615953-a4cea680-a901-11eb-8fec-3c05799351bf.png)

**Comment by bchetwynd** [comment]
Glad to hear!
