### ISSUE TITLE
GPS Pcode Issue

### ISSUE THREAD

**Issue by KeethSmith** [mit-ll/CEP#13]
When compiling and running the make command on the basic gps_sim test. The test fails all cases. I believe this is because the expected vs. actual keys differ by 9 bits in the P-code region.

**Comment by bchetwynd** [comment]
We are in the process of a major overhaul of the project, migrating to UCB's Chipyard with significant upgrades to the simulation environment.  As part of that, we have updates to the GPS tests that are actually compliant with the standard.

**Comment by arlted** [comment]
Hi, Is there a time frame when the migration could happen? I am interested in using the most-up-to-date CEP design and simulation environment for a project.

**Comment by bchetwynd** [comment]
Hello.  My hope is to have the Chipyard-based CEP released in ~1 month.  We are in the process of standing up an FPGA version, which is essential to the open source release.

**Comment by bchetwynd** [comment]
With CEP v4.2, the pcode work properly for the first GPS core, but will fail on subsequent ones (in the same simulation).  A patch will be released with the next CEP update.

**Comment by bchetwynd** [comment]
This issue has been address in CEP v4.3, which is located at the new CEP repository location
