### ISSUE TITLE
Status of CEP migration

### ISSUE THREAD

**Issue by arlted** [mit-ll/CEP#14]
Hi,
I read a comment in another thread that a more up-to-date CEP will be migrating to UCB'sChip Yard.
Is there a time frame when the migration could happen? I am interested in using the most-up-to-date CEP design and silumation environment for a project that involves ASIC.

Thanks,
Ted

**Comment by bchetwynd** [comment]
As noted in #13, I expected it to be in ~1 month.  We are in the process of standing up an FPGA version of the Chipyard-CEP, which is essential to the open source release.

**Comment by arlted** [comment]
Thank you.  Will the Chipyard-CEP have an ASIC version too?

Regards,
Ted
________________________________
From: Brendon Chetwynd ***@***.***>
Sent: Monday, June 6, 2022 6:56 AM
To: mit-ll/CEP ***@***.***>
Cc: Nigussie, Theodros B CIV USARMY DEVCOM ARL (USA) ***@***.***>; Author ***@***.***>
Subject: [URL Verdict: Neutral][Non-DoD Source] Re: [mit-ll/CEP] Status of CEP migration (Issue #14)


All active links contained in this email were disabled. Please verify the identity of the sender, and confirm the authenticity of all links contained within the message prior to copying and pasting the address to a Web browser.


________________________________



As noted in #13 < Caution-https://github.com/mit-ll/CEP/issues/13 > , I expected it to be in ~1 month. We are in the process of standing up an FPGA version of the Chipyard-CEP, which is essential to the open source release.

**Comment by bchetwynd** [comment]
Ted,

I think you'll need to clarify your question.   In the case of the FPGA target, we'll be releasing a build on the Arty A7-100T, with a goal of releasing a more capable version on the VCU118 in the future.

On the ASIC front, any libraries/IP need to be licensed... as was the case with our recent tapeout.  We have a long-term goal of releasin a licensed unencumbered ASIC version, but that is a while out.

**Comment by arlted** [comment]
Sorry, my question was not clear. I meant to ask about the "licensed unencumbered ASIC version" and you have answered it.

Thank you.
________________________________
From: Brendon Chetwynd ***@***.***>
Sent: Monday, June 6, 2022 8:27 AM
To: mit-ll/CEP ***@***.***>
Cc: Nigussie, Theodros B CIV USARMY DEVCOM ARL (USA) ***@***.***>; Author ***@***.***>
Subject: [URL Verdict: Unknown][Non-DoD Source] Re: [mit-ll/CEP] Status of CEP migration (Issue #14)

All active links contained in this email were disabled. Please verify the identity of the sender, and confirm the authenticity of all links contained within the message prior to copying and pasting the address to a Web browser.

________________________________



Ted,

I think you'll need to clarify your question. In the case of the FPGA target, we'll be releasing a build on the Arty A7-100T, with a goal of releasing a more capable version on the VCU118 in the future.

On the ASIC front, any libraries/IP need to be licensed... as was the case with our recent tapeout. We have a long-term goal of releasin a licensed unencumbered ASIC version, but that is a while out.
