### ISSUE TITLE
get_external_dependencies.sh uses exit 1 on successful completion

### ISSUE THREAD

**Issue by vivekmalneedi** [mit-ll/CEP#6]
`get_external_dependencies.sh` returns with exit code 1 on both error and successful completion

It should instead use `exit 0` whenever the script successfully downloads the dependencies or displays the help message

Additionally, line 236 of the readme has `build` written as `b0uild`

Thanks

**Comment by bchetwynd** [comment]
Thanks, Vivek.  I will roll it into the next release.
