### ISSUE TITLE
Getting stuck at 'BOOT'

### ISSUE THREAD

**Issue by Iripi97** [mit-ll/CEP#9]
I followed the instructions in the repo and generated the bit-stream, mcs file, prm file, and the bbl.bin file. When I boot up my VC707 I can see the CEP logo with some information and it continues to display the following:

INIT
CMD0
CMD8
ACMD41
CMD58
CMD16
CMD18
LOADING
BOOT

But then it just sits there. Is the VC707 supposed to have any additional hardware (like the FMC card)? All I am using is a VC707 w/ its power supply, JTAG cable, UART cable, and SD card. I am unsure why it is getting "frozen" in this state when the building of all the files was successful.

**Comment by bchetwynd** [comment]
No, the CEP is built with the no-FMC option (VC707BaseShell) in ./hdl_cores/freedom/Makefile.vc707-u500devkit.  If the FMC was required and you didn't have it, you would even see what you see.

It sounds like your SD card is not properly formatted....

Did you go through the steps of "Building the CEP Diagnostics Software"??? 

... which ends in the following step?

`sudo make DISK=/dev/<your SD card> vc707-sd-write`

**Comment by Iripi97** [comment]
Is "<your SD card>" the name of the SD card (say **sdb**) or is it supposed to be the 1st partition (say **sdb1**). Also should the _sudo make DISK=/dev/<your SD card> format-boot-loader_ command be skipped (it is mentioned at the end of running "make -jN BOARD=vc707devkit_nopci all" in the terminal output).

**Comment by bchetwynd** [comment]
Name of your SD card and yes, it should be sudo (given you are writing to a raw device

Example: `sudo make DISK=/dev/sdc vc707-sd-write`

**Comment by Iripi97** [comment]
Hahaha how silly, when I did that the first time it did not work. I just did it now and it is working! Thank you very much.
